title:             Clean Blog
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
baseurl:           "startbootstrap-clean-blog-jekyll"
url:               ""

# Social Profiles
twitter-username:  SBootstrap
facebook-username: StartBootstrap
github-username:   BlackrockDigital

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
